### ISSUE TITLE
Unbound variable

### ISSUE THREAD

**Issue by Mark-Labuschagne** [jembi/platform#211]
If the environment variable file does not specify `CLUSTERED_MODE=...`, the error `unbound variable` is thrown. This variable should have a default value in the package-metadata.json file.

Got the error when deploying Kibana.

**Comment by michaelloosen** [comment]
Yeah, there was a discussion to remove it from the `package-metadata.json` file, but no alternative solution was implemented, I agree, we need to have a default for this, but I also agree that we shouldn't have it at a package level, so we'll need to give this some thought.

**Comment by Mark-Labuschagne** [comment]
Closing this issue, it was decided that there are certain env vars that the user must be explicit about setting. The error thrown when not setting those env vars is informative enough to pin point the issue.
